version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev123
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - ../.env.common
    depends_on:
      - postgres

  websocket:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.websocket 
    ports:
      - "8081:8081"
    env_file:
      - ../.env.common
    depends_on:
      - postgres

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
      args:
          DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ../.env.common
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  db_data:
