name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
    #   - name: Docker login
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    # #   - name: Build and push
    # #     uses: docker/build-push-action@v4
    # #     with:
    # #       context: .
    # #       file: ./docker/Dockerfile.backend
    # #       push: true
    # #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-docker-backend:${{ github.sha }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Install Docker (if not installed)
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
              sudo usermod -aG docker $USER
              newgrp docker
            fi

            # Install Node.js (if not installed)
            if ! command -v node &> /dev/null; then
              echo "Node.js not found. Installing..."
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Pull and deploy the Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-docker-backend:${{ github.TEST_DOCKER_TAG }}
            docker stop monorepo-backend || true
            docker rm monorepo-backend || true
            docker run -d --name monorepo-backend \
              -p 8000:8000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-docker-backend:${{ github.TEST_DOCKER_TAG }}
